### ISSUE TITLE
Apps crash on user interaction [$20]

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#76]
This affects the Green Island sample compositor, Hawaii Shell, and the Green Island port of Papyros. I'm running the shell using `greenisland --shell org.greenisland.simple` on top of X11 and GNOME 3.16.

**Steps to reproduce**
 1. Open the sample compositor
 2. Open a Gtk or QML app. The app opens in the compositor
 3. Drag the window. Interacting with the window often causes this crash as well
 4. The compositor segfaults and the app terminates

**App logs**

    $ nautilus

    (nautilus:4798): Gdk-WARNING **: Error 75 (Value too large for defined data type) dispatching to Wayland display.

**Green Island logs** 

See https://gist.github.com/iBeliever/941dd436783c93ab1f1b

**Comment by iBeliever** [comment]
I've also been able to reproduce this with QML apps launched via `qmlscene`. I get the same "value to large" error.

**Comment by plfiorini** [comment]
Something with the pointer judging from the stack trace, investigating...

**Comment by iBeliever** [comment]
@plfiorini Any update on this?

**Comment by plfiorini** [comment]
Not yet, been hunting down a bug in eglfs instead

**Comment by VirusKA** [comment]
This is such a weird bug

**Comment by iBeliever** [comment]
@plfiorini When do you think you'll have a fix for this? This is really a major blocker for using any Green Island-based compositor.

**Comment by plfiorini** [comment]
As soon as I understand what's going on...

**Comment by plfiorini** [comment]
btw @iBeliever use this team for bounties https://www.bountysource.com/teams/hawaii/issues

**Comment by plfiorini** [comment]
Stack trace

```
(gdb) bt
#0  0x0000000000960730 in  ()
#1  0x00007ffff72aa72a in QtWayland::Pointer::setMouseFocus(QWaylandSurfaceView*, QPointF const&, QPointF const&) (this=0x7ca070, surface=0x0, localPos=..., globalPos=...) at wayland_wrapper/qwlpointer.cpp:232
#2  0x00007ffff72aa47b in QtWayland::Pointer::focusDestroyed(void*) (this=0x7ca070, data=0x961bd0) at wayland_wrapper/qwlpointer.cpp:140
#3  0x00007ffff72ab460 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<void*>, void, void (QtWayland::Pointer::*)(void*)>::call(void (QtWayland::Pointer::*)(void*), QtWayland::Pointer*, void**) (f=
    (void (QtWayland::Pointer::*)(QtWayland::Pointer * const, void *)) 0x7ffff72aa40a <QtWayland::Pointer::focusDestroyed(void*)>, o=0x7ca070, arg=0x7fffffffcf70) at /opt/qt5/include/QtCore/qobjectdefs_impl.h:501
#4  0x00007ffff72ab3e1 in QtPrivate::FunctionPointer<void (QtWayland::Pointer::*)(void*)>::call<QtPrivate::List<void*>, void>(void (QtWayland::Pointer::*)(void*), QtWayland::Pointer*, void**) (f=
    (void (QtWayland::Pointer::*)(QtWayland::Pointer * const, void *)) 0x7ffff72aa40a <QtWayland::Pointer::focusDestroyed(void*)>, o=0x7ca070, arg=0x7fffffffcf70) at /opt/qt5/include/QtCore/qobjectdefs_impl.h:520
#5  0x00007ffff72ab2d3 in QtPrivate::QSlotObject<void (QtWayland::Pointer::*)(void*), QtPrivate::List<void*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x7c9d30, r=0x7ca070, a=0x7fffffffcf70, ret=0x0) at /opt/qt5/include/QtCore/qobject_impl.h:143
#6  0x00007ffff6adf937 in QMetaObject::activate(QObject*, int, int, void**) (a=0x7fffffffcf70, r=0x7ca070, this=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
#7  0x00007ffff6adf937 in QMetaObject::activate(QObject*, int, int, void**) (sender=0x7ca120, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3712
#8  0x00007ffff72f6319 in WlListener::fired(void*) (this=0x7ca120, _t1=0x961bd0) at .moc/moc_qwllistener_p.cpp:125
#9  0x00007ffff72bb96d in WlListener::handler(wl_listener*, void*) (listener=0x7ca130, data=0x961bd0) at wayland_wrapper/qwllistener.cpp:59
#10 0x00007ffff57c4364 in destroy_resource () at /lib64/libwayland-server.so.0
#11 0x00007ffff59d90ed in wl_map_for_each () at /lib64/libwayland-client.so.0
#12 0x00007ffff57c4fc8 in wl_client_destroy () at /lib64/libwayland-server.so.0
#13 0x00007ffff57c5278 in wl_client_connection_data () at /lib64/libwayland-server.so.0
#14 0x00007ffff57c6fb2 in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#15 0x00007ffff72959da in QtWayland::Compositor::processWaylandEvents() (this=0x7c6c00) at wayland_wrapper/qwlcompositor.cpp:266
#16 0x00007ffff72f5844 in QtWayland::Compositor::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7c6c00, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffd410) at .moc/moc_qwlcompositor_p.cpp:74
#17 0x00007ffff6adfaaa in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x7c73e0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd410) at kernel/qobject.cpp:3727
#18 0x00007ffff6ae02a7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x7c73e0, m=m@entry=0x7ffff6cf9a80 <QSocketNotifier::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd410) at kernel/qobject.cpp:3592
#19 0x00007ffff6b5ad3e in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) (this=this@entry=0x7c73e0, _t1=10) at .moc/moc_qsocketnotifier.cpp:134
#20 0x00007ffff6aebe7b in QSocketNotifier::event(QEvent*) (this=0x7c73e0, e=<optimized out>) at kernel/qsocketnotifier.cpp:296
#21 0x00007ffff6ab2f79 in QCoreApplication::notify(QObject*, QEvent*) (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1026
#22 0x00007ffff6ab3093 in QCoreApplication::notifyInternal(QObject*, QEvent*) (this=0x7fffffffd7e0, receiver=0x7c73e0, event=event@entry=0x7fffffffd4f0) at kernel/qcoreapplication.cpp:964
#23 0x00007ffff6b0699d in socketNotifierSourceDispatch(GSource*, GSourceFunc, gpointer) (event=0x7fffffffd4f0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
#24 0x00007ffff6b0699d in socketNotifierSourceDispatch(GSource*, GSourceFunc, gpointer) (source=0x7ad740) at kernel/qeventdispatcher_glib.cpp:100
#25 0x00007ffff1221a8a in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00007ffff1221e20 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#27 0x00007ffff1221ecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#28 0x00007ffff6b064ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7ad5b0, flags=...) at kernel/qeventdispatcher_glib.cpp:417
#29 0x00007ffff6ab0c1a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffd6f0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#30 0x00007ffff6ab873d in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1217
#31 0x00000000004033c8 in main ()
```

**Comment by plfiorini** [comment]
The weird part is that I cannot reproduce with Hawaii.

**Comment by plfiorini** [comment]
From the stack trace this seems a problem on QtCompositor though.

**Comment by VirusKA** [comment]
any luck?

**Comment by plfiorini** [comment]
This is fixed for a while now
